apiVersion: v1
kind: Service
metadata:
  name: hello-world
  namespace: demo
  labels:
    app: hello-world
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: hello-world
    track: stable
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: hello-world
    track: stable
  name: hello-world
  namespace: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hello-world
        track: stable
    spec:
      containers:
      - name: hello-world
        image: jdeskins/hello-node:1.0
        resources:
          limits:
            cpu: 250m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 64Mi
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 3
          timeoutSeconds: 1
