apiVersion: v1
kind: Service
metadata:
  name: hello-app
  labels:
    app: hello-app
spec:
  type: NodePort
  ports:
  - port: 8080
  selector:
    run: hello-app
    track: stable
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: hello-app
    track: stable
  name: hello-app
spec:
  replicas: 2
  selector:
    matchLabels:
      run: hello-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: hello-app
        track: stable
    spec:
      containers:
      - name: hello-app
        image: jdeskins/hello-node:1.0
#        resources:
#          limits:
#            cpu: 250m
#            memory: 128Mi
#          requests:
#            cpu: 100m
#            memory: 64Mi
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 1
