apiVersion: v1
kind: Service
metadata:
  name: node-demo
  labels:
    app: node-demo
spec:
  # if your cluster supports it, use type: LoadBalancer to automatically create
  # an external load-balanced IP for the frontend service.
  #type: LoadBalancer
  type: NodePort
  ports:
  - port: 8080
  selector:
    run: node-demo
    track: stable
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: node-demo
    track: stable
  name: node-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      run: node-demo
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: node-demo
        track: stable
    spec:
      containers:
      - name: node-demo
        image: jdeskins/node-demo:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "200m"
            memory: "128Mi"
