apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: hello-app
    tier: stable
    version: v2
  name: hello-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-app
      version: v2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: hello-app
        tier: stable
        version: v2
    spec:
      containers:
      - name: hello-app
        image: jdeskins/hello-node:2.0
        resources:
          limits:
            cpu: 250m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 64Mi
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 1
#      nodeSelector:
#        app: demo
